<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="117.964" tests="2" failures="2">
  <testsuite name="Root Suite" timestamp="2023-01-05T08:41:22" tests="0" file="cypress\e2e\Entscheid Copy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Test to copy Entscheid with all data https://osiv-frtest.ivnet.ch" timestamp="2023-01-05T08:41:22" tests="2" time="117.940" failures="2">
    <testcase name="Test to copy Entscheid with all data https://osiv-frtest.ivnet.ch Open Entscheid and copy" time="0.000" classname="Open Entscheid and copy">
      <failure message="Timed out retrying after 50000ms: Expected to find element: `[class=&quot;dhx_toolbar_btn dhxtoolbar_btn_pres&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 50000ms: Expected to find element: `[class="dhx_toolbar_btn dhxtoolbar_btn_pres"]`, but never found it.
    at Object.HomeBtn (webpack:///./cypress/support/page_objects/Dashboard.js:7:14)
    at Context.eval (webpack:///./cypress/e2e/Entscheid Copy.js:45:14)]]></failure>
    </testcase>
    <testcase name="Test to copy Entscheid with all data https://osiv-frtest.ivnet.ch Compare responses of copied Entscheid" time="0.000" classname="Compare responses of copied Entscheid">
      <failure message="`cy.task(&apos;getEntscheidIdNM&apos;)` failed with the following error:

The task &apos;getEntscheidIdNM&apos; returned undefined. You must return a value, null, or a promise that resolves to a value or null to indicate that the task was handled.

The task handler was:

() =&gt; {
            return EntscheidIdNM;
          }

Fix this in your setupNodeEvents method here:
C:\osiv-cypress-tests\cypress.config.js

https://on.cypress.io/api/task" type="CypressError"><![CDATA[CypressError: `cy.task('getEntscheidIdNM')` failed with the following error:

The task 'getEntscheidIdNM' returned undefined. You must return a value, null, or a promise that resolves to a value or null to indicate that the task was handled.

The task handler was:

() => {
            return EntscheidIdNM;
          }

Fix this in your setupNodeEvents method here:
C:\osiv-cypress-tests\cypress.config.js

https://on.cypress.io/api/task
    at <unknown> (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:144427:80)
    at tryCatcher (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:11327:23)
    at Promise._settlePromiseFromHandler (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:9262:31)
    at Promise._settlePromise (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:9319:18)
    at Promise._settlePromise0 (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:9364:10)
    at Promise._settlePromises (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:9440:18)
    at _drainQueueStep (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:6034:12)
    at _drainQueue (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:6027:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:6043:5)
    at Async.drainQueues (https://osiv-frtest.ivnet.ch/__cypress/runner/cypress_runner.js:5913:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/Entscheid Copy.js:69:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>